# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_short', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_short', models.CharField(max_length=200)),
                ('phenotype', models.CharField(max_length=500)),
                ('function', models.TextField(null=True)),
                ('gpcrfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpcr_family', to='core.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('name_short', models.CharField(max_length=100)),
                ('inchi_key', models.CharField(max_length=200)),
                ('chem_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('sequence', models.TextField()),
                ('reference_id', models.CharField(max_length=45)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Family')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.TextField()),
                ('citation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Source'),
        ),
        migrations.AddField(
            model_name='interactions',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ligand'),
        ),
        migrations.AddField(
            model_name='interactions',
            name='rampfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramp_family', to='core.Family'),
        ),
        migrations.AddField(
            model_name='interactions',
            name='reference',
            field=models.ManyToManyField(null=True, to='core.Reference'),
        ),
    ]
